import Providers from "@/components/providers/providers";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToggleTheme from "@/components/common/toggle-theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "404 Brain Not Found ",
  description: "Generated by 404 Brain Not Found ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-bl dark:from-gray-900 dark:to-black flex flex-col min-h-dvh p-2`}
      >
        <Providers>
          <ToggleTheme className="self-end" />
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
